// components/TransactionModal.styles.js
import { StyleSheet } from "react-native";
import { COLORS } from "../../constants/color";

export default StyleSheet.create({
    modalBackground: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalContainer: {
        width: "90%",
        backgroundColor: COLORS.white,
        borderRadius: 20,
        padding: 20,
    },
    title: {
        fontSize: 22,
        fontWeight: "bold",
        marginBottom: 15,
        textAlign: "center",
    },
    input: {
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 10,
        padding: 10,
        marginBottom: 15,
    },
    label: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 10,
    },
    categoryItem: {
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 20,
        paddingVertical: 6,
        paddingHorizontal: 12,
        marginRight: 10,
        backgroundColor: "#f5f5f5",
    },
    categoryItemSelected: {
        color: COLORS.white,
        fontWeight: "bold",
    },
    amountRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 15,
    },
    amountLabel: {
        fontSize: 16,
        fontWeight: "600",
        marginRight: 10,
        width: 180,
    },
    amountInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 10,
        padding: 10,
        textAlign: "center",
    },
    dateRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 5,
    },
    dateButton: {
        flex: 1,
        backgroundColor: "#b3f0f0ff",
       
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 10,
        alignItems: "center",
    },
    dateButtonText: {
        color: COLORS.white,
        fontWeight: "bold",
        fontSize: 14,
    },
    actionRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 15,
    },
    cancelButton: {
        flex: 1,
        backgroundColor: "#f0f0f0",
        paddingVertical: 10,
        borderRadius: 20,
        alignItems: "center",
        marginRight: 8,
    },
    cancelButtonText: {
        color: "#555",
        fontWeight: "600",
        fontSize: 14,
    },
    saveButton: {
        flex: 1,
        backgroundColor: COLORS.primary,
        paddingVertical: 10,
        borderRadius: 20,
        alignItems: "center",
    },
    saveButtonText: {
        color: COLORS.white,
        fontWeight: "600",
        fontSize: 14,
    },
    modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.4)' },
    overlayFill: { flex: 1 },
    bottomSheet: {
        backgroundColor: COLORS.white,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 24,
        elevation: 6,
    },
    sheetTitle: { fontSize: 16, fontWeight: '700', color: '#111', marginTop: '2%', marginBottom: 8 },
    button: {
        backgroundColor: COLORS.primaryLight,
        padding: 15,
        alignItems: 'center',
        borderRadius: 15,
        width: '100%',
    },

    buttonText: {
        color: COLORS.white,
        fontSize: 18,
        fontWeight: 'bold',
    },
    closeBtn: {
        position: 'absolute',
        right: 12,
        top: 12,
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
    },
    topRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        marginBottom: 15,
    },
    iconClose: {
        width: 40,
        height: 40,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: COLORS.borderWhite,
    },
    buttonContainer: {
        marginTop: 12,
        marginBottom: 8,
        width: '100%',
    },
});
